commonOverlays:
  - name: "add namespace markers"
    query:
      - metadata.namespace
      - subjects[*].namespace
    value: "%v"  # +operator-builder:field:name=namespace,default="%v",type=string

yamlFiles:
  - name: "zalando-postgres configmap"
    path: "../vendor/config.yaml"
    outputPath: "manifests/config.yaml"

  - name: "zalando-postgres deployment"
    path: "../vendor/deployment.yaml"
    outputPath: "manifests/deployment.yaml"
    overlays:
      - name: "add replica count marker"
        query: "$"
        value:
          spec:
            # +operator-builder:field:name=zalandoPostgres.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the postgres-operator deployment.`
            replicas: !!int "%v"

      - name: "add image name markers"
        query: "spec.template.spec.containers[?(@.name == 'postgres-operator')]"
        value:
          # +operator-builder:field:name=zalandoPostgres.image,default={{ .defaultImage }},type=string,replace="postgresImage",description=`
          # Image repo and name to use for postgres operator.`
          # +operator-builder:field:name=zalandoPostgres.version,default={{ .defaultVersion }},type=string,replace="postgresVersion",description=`
          # Version of postgres operator to use.`
          image: postgresImage:postgresVersion

  - name: "zalando-postgres rbac"
    path: "../vendor/rbac.yaml"
    outputPath: "manifests/rbac.yaml"

  - name: "zalando-postgres service"
    path: "../vendor/service.yaml"
    outputPath: "manifests/service.yaml"

