---
# +operator-builder:resource:field=kong.include,value=true,include
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kong
  labels:
    platform.nukleros.io/category: ingress
    platform.nukleros.io/project: kong-ingress-controller
spec:
  controller: ingress-controllers.konghq.com/kong
