---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  labels:
    application: postgres-operator
    app.kubernetes.io/name: postgres-operator
    application.nukleros.io/group: database
    application.nukleros.io/project: zalando-postgres
  namespace: nukleros-database-system # +operator-builder:field:name=namespace,default="nukleros-database-system",type=string
spec:
  # +operator-builder:field:name=zalandoPostgres.replicas,default="1",type=int,description=`
  # Number of replicas to use for the postgres-operator deployment.`
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
        app.kubernetes.io/name: postgres-operator
        application.nukleros.io/group: database
        application.nukleros.io/project: zalando-postgres
    spec:
      serviceAccountName: postgres-operator
      containers:
        - name: postgres-operator
          # +operator-builder:field:name=zalandoPostgres.image,default=registry.opensource.zalan.do/acid/postgres-operator,type=string,replace="postgresDefaultImage",description=`
          # Image repo and name to use for postgres operator.`
          # +operator-builder:field:name=zalandoPostgres.version,default=v1.8.2,type=string,replace="postgresDefaultVersion",description=`
          # Version of postgres operator to use.`
          image: postgresDefaultImage:postgresDefaultVersion
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 500m
              memory: 500Mi
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          env:
            - name: CONFIG_MAP_NAME
              value: postgres-operator
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - nginx-ingress
      nodeSelector:
        kubernetes.io/os: linux
