---
defaultCainjectorImage: quay.io/jetstack/cert-manager-cainjector
defaultControllerImage: quay.io/jetstack/cert-manager-controller
defaultWebhookImage: quay.io/jetstack/cert-manager-webhook
defaultVersion: v1.9.1

