apiVersion: platform.addons.nukleros.io/v1alpha1
kind: SecretsComponent
metadata:
  name: secretscomponent-sample
spec:
  #collection:
    #name: "supportservices-sample"
    #namespace: ""
  externalSecrets:
    include: true
    version: "v0.5.9"
    certController:
      replicas: 1
    image: "ghcr.io/external-secrets/external-secrets"
    controller:
      replicas: 2
    webhook:
      replicas: 2
  reloader:
    include: true
    replicas: 1
    image: "stakater/reloader"
    version: "v0.0.119"
  namespace: "nukleros-secrets-system"
