commonOverlays:
  - name: "add namespace markers"
    query:
      - metadata.namespace
      - subjects[*].namespace
    value: "%v"  # +operator-builder:field:name=namespace,default="%v",type=string

yamlFiles:
  - name: "reloader deployment"
    path: "../vendor/deployment.yaml"
    outputPath: "manifests/deployment.yaml"
    overlays:
      - name: "add reloader image markers"
        query: "spec.template.spec.containers[*]"
        value:
          # +operator-builder:field:name=reloader.image,default={{ .defaultImage }},type=string,replace="reloaderImage",description=`
          # Image repo and name to use for reloader.`
          # +operator-builder:field:name=reloader.version,default="{{ .defaultVersion }}",type=string,replace="reloaderVersion",description=`
          # Version of reloader to use.`
          image: reloaderImage:reloaderVersion

      - name: "add reloader replica count marker"
        query: "$[?($.metadata.name == 'secret-reloader')]"
        value:
          spec:
            # +operator-builder:field:name=reloader.replicas,default="%v",type=int,description=`
            # Number of replicas to use for the reloader deployment.`
            replicas: !!int "%v"

      - name: "add include marker for reloader project"
        query: "$"
        value:
          # +operator-builder:resource:field=reloader.include,value=true,include
          apiVersion: apps/v1

  - name: "reloader rbac"
    path: "../vendor/rbac.yaml"
    outputPath: "manifests/rbac.yaml"
    overlays:
      - name: "add include marker on service account for reloader project"
        documentQuery:
          - conditions:
              - query: kind
                value: ServiceAccount
        query: "$"
        value:
          # +operator-builder:resource:field=reloader.include,value=true,include
          apiVersion: v1

      - name: "add include marker on cluster role and binding for reloader project"
        documentQuery:
          - conditions:
              - query: kind
                value: ClusterRole
          - conditions:
              - query: kind
                value: ClusterRoleBinding
        query: "$"
        value:
          # +operator-builder:resource:field=reloader.include,value=true,include
          apiVersion: rbac.authorization.k8s.io/v1

