---
# +operator-builder:field:name=tier,arbitrary,default="development",type=string,description=`
# +kubebuilder:validation:Enum=development;staging;production
# The tier of cluster being used.  One of: development | staging | production.`
apiVersion: v1
kind: Namespace
metadata:
  name: nukleros-support-services-system  # +operator-builder:field:parent=metadata.name,type=string
