---
apiVersion: v1
kind: Namespace
metadata:
  # +operator-builder:field:name=namespace,default="nukleros-ingress-system",type=string,description=`
  # Namespace to use for ingress support services.`
  name: nukleros-ingress-system
  labels:
    externalDNSProvider: none # +operator-builder:field:name=externalDNS.provider,type=string
